osk: don't redefine bool and use the standard one instead
In nixos/nixpkgs we now got these errors:
```
Onboard/osk/osk_module.h:28:16: error: expected identifier before numeric constant
   28 | typedef enum { false, true } bool;
      |                ^~~~~
Onboard/osk/osk_module.h:28:30: error: expected ‘;’, identifier or ‘(’ before ‘_Bool’
   28 | typedef enum { false, true } bool;
      |                              ^~~~
```
which indicates that someone (a header included before `osk_module.h`, perhaps transitively)
most likely included `stdbool.h` and thus this typedef got broken.
But I haven't tried to analyze the cause that much.

Either way, the line I'm deleting was rather ugly and fragile.